@baseUrl = http://localhost:8000/auth

POST {{baseUrl}}/signin
Content-Type: application/json

{
  "name": "John Doe",
  "username": "john_d",
  "password": "123456"
}

###

POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=john_d
&password=123456
