@baseUrl = http://localhost:8000/tarefas

GET {{baseUrl}}
Authorization: Bearer <jwt_token>

###

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer <jwt_token>

{
  "title": "Estudar Python"
}

###

PATCH {{baseUrl}}/2
Content-Type: application/json
Authorization: Bearer <jwt_token>

{
  "done": "yes"
}

###

DELETE {{baseUrl}}/2
Authorization: Bearer <jwt_token>
