@baseUrl = http://localhost:8000/tarefas

GET {{baseUrl}}
Authorization: Bearer <jwt_token>

###

GET {{baseUrl}}/2

###

POST {{baseUrl}}
Content-Type: application/json

{
  "title": "Estudar Python",
  "user_id": 0
}

###

PATCH {{baseUrl}}/2
Content-Type: application/json

{
  "done": "yes"
}

###

DELETE {{baseUrl}}/2
